version: "2.3"

services:

  docker-mysql:
    image: mysql:latest
   
    
    ports:
    - 3306:3306

    environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=root
    - MYSQL_PASSWORD=1234

  springbootapp:

    ports:
      - 8080:8080

    image: dockerlab

    depends_on:
    - docker-mysql

    environment:
    - DATABASE_HOST=docker-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=1234
    - DATABASE_NAME=tema2aos
    - DATABASE_PORT=3306